### ISSUE TITLE
No pymakr version for latest Atom 1.40.1

### ISSUE THREAD

**Issue by samkalnins** [pycom/pymakr-atom#132]
It's not possible to install pymakr in the latest production release of Atom (1.40.1) -- since pymakr specifies it only supports Atom <1.40.0

Can we have a pymakr version which supports >1.40.0?

Thanks!

<img width="735" alt="Screen Shot 2019-08-24 at 12 29 48 PM" src="https://user-images.githubusercontent.com/7118540/63641904-f4f46080-c66a-11e9-91ba-145272cd0df6.png">

**Comment by RalphHogenbirk** [comment]
This has been solved with the release of 1.4.15 that was done this morning.

**Comment by jdcrunchman** [comment]
Ralph...  this fix does not work.   I installed a new Atom,  1.40.1 X64.   Tried to install the new pymakr 1.4.16.    I get the usual error message....
![Screen Shot 2019-09-20 at 12 13 33 PM](https://user-images.githubusercontent.com/3130169/65352720-272cab80-dba0-11e9-982c-0b7ac3cd50c2.png)
as seen from this screenshot.   Has there, been any workarounds posted?    One in which I can actually figure out how to deploy it?

it shows this issue has already been reported....  OK,  so can anyone please give me SOME workaround?    I'm already delayed by 3 weeks on this project I've been working on.

Can you tell me the name of the developer actually working on this bug,  and how I can reach them,  I will be happy to help them debug it....   PLEASE PLEASE....HELP...  ME

So Ralph,  this problem has NOT been solved,  and would appreciate it if I can have a one-on-ine conversation with you to help me out.

I will be willing to pay for your time (as long as it's reasonable).   Or do you have other workarounds posted?

Anyway, as far as I'm concerned this issue is NOT closed.

**Comment by jdcrunchman** [comment]
RalphHogenbirk  - can you please reach out to me and help me get my Dev system running again.
Please contact me via Signal,  Telegram,  WhatsApp,  or even POTS at the following phone number,  or email me at jdcrunchman at protonmail dot com or jdcrunchman at gmail dot com.

isn't there ANY workaround?

**Comment by pedroknup** [comment]
Hi guys. A new version (1.5.0) has been released yesterday that might fix all the compatibility issues from Atom 1.35.0 to 1.42.0 (nightly). Please try it out and drop a message here saying how it went.
