### ISSUE TITLE
File sync ignores symlinked folders

### ISSUE THREAD

**Issue by martijnthe** [pycom/pymakr-atom#87]
I've a symlink'd folder in my project but pymakr's sync refuses to sync the files that the symlink points to. The use case: I've got a git submodule in the project, but only want to sync a subfolder of it. Therefore I created a symlink to the folder I want to sync.

**Comment by RalphHogenbirk** [comment]
Hey @martijnthe, You're right, symlinks are being ignored at the moment. Fix turns out to be very simple, so I pushed it to the develop branch. Feel free to test the code from there, or wait for the next release which will include this.

https://github.com/pycom/pymakr-atom/commit/abf1cd2f285d122a30ef67b8444acf51b35cbb30

**Comment by martijnthe** [comment]
Thanks, I'll try it out
